[package]
name = "unlocker"
version = "0.0.1"
authors = [ "@RisaSoftStaking",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"
